#!/usr/bin/perl
use File::Find;
use Test::More qw/no_plan/;

find(\&wanted, "./");

sub wanted {
 if ($_ =~ /\.dir$/ || $_ =~ /\.pag$/) {
   system("unlink $_");
 }
}

 is(1,1); #just to quiet the test harness ;)